# db-refresh-main.ps1

$ErrorActionPreference = "Stop"

# Resolve paths relative to this script file.
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$SchemaDir = Join-Path $ScriptDir "public"
$MainSqlPath = Join-Path $ScriptDir "main.sql"

if (-not (Test-Path $SchemaDir)) {
    throw "Schema directory not found: $SchemaDir"
}

$preferredOrder = @(
    "public/user_account.sql",
    "public/player_profile.sql",
    "public/command_profile.sql",
    "public/campaign.sql",
    "public/campaign_turn.sql",
    "public/campaign_snapshot.sql",
    "public/campaign_command.sql",
    "public/campaign_event.sql",
    "public/career_record.sql"
)

# Find all table-definition .sql files under /public, excluding manual extension
# setup and optional native constraint scripts that should remain separate
# deployment steps if added.
$sqlFiles = Get-ChildItem -Path $SchemaDir -Recurse -Filter "*.sql" |
    Where-Object {
        $_.Name -ne "extensions.sql" -and
        -not $_.FullName.StartsWith((Join-Path $SchemaDir "constraints"), [System.StringComparison]::OrdinalIgnoreCase)
    }

$relativeSqlFiles = $sqlFiles |
    ForEach-Object {
        [System.IO.Path]::GetRelativePath($ScriptDir, $_.FullName).Replace("\", "/")
    }

$orderedSqlFiles = @()

foreach ($path in $preferredOrder) {
    if ($relativeSqlFiles -contains $path) {
        $orderedSqlFiles += $path
    }
}

$orderedSqlFiles += $relativeSqlFiles |
    Where-Object { $preferredOrder -notcontains $_ } |
    Sort-Object

$lines = @()

foreach ($relativePath in $orderedSqlFiles) {
    $lines += "-- atlas:import $relativePath"
}

$lines += ""
$lines += "-- IMPORTANT: The import directives above must stay at the top of this file for Atlas."
$lines += "-- Auto-generated by db-refresh-main.ps1"
$lines += "-- Do not edit manually."
$lines += "-- Generated at: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss zzz")"
$lines += ""

Set-Content -Path $MainSqlPath -Value $lines -Encoding UTF8

Write-Host "Refreshed SandTable main.sql with $($orderedSqlFiles.Count) SQL file(s)."
Write-Host "Path: $MainSqlPath"
