-- atlas:import public/user_account.sql
-- atlas:import public/player_profile.sql
-- atlas:import public/command_profile.sql
-- atlas:import public/campaign.sql
-- atlas:import public/campaign_turn.sql
-- atlas:import public/campaign_snapshot.sql
-- atlas:import public/campaign_command.sql
-- atlas:import public/campaign_event.sql
-- atlas:import public/career_record.sql

-- IMPORTANT: The import directives above must stay at the top of this file for Atlas.
-- Auto-generated by db-refresh-main.ps1
-- Do not edit manually.
-- Generated at: 2026-07-07 20:37:46 +12:00

